# Generated by Django 4.2.5 on 2023-09-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DifferenceStatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=0)),
                ('last_datetime', models.DateTimeField(blank=True)),
            ],
        ),
    ]
